#!/bin/bash

export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:${PWD}/src
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:${PWD}/test
# export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:${HOME}/anaconda3/lib/python3.9/site-packages/torch/include
# export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH=${HOME}/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include
